# This file is used to store the configuration for the cloudspeech program. It contains configuration for all the components of the program. The configuration is stored in the form of key-value pairs. The keys are the names of the components and the values are the configuration for the components. It is important to note that the configuration is stored in the form of a dictionary. The configuration file is used to store the configuration for the following components:
# 1. General configuration options for the program
# 2. Google Cloud Speech API
# 3. OpenAI GPT model information
# 4. Elevenlabs API information

# 0. ROBOT
robot:
  use_robot: False ## Whether to use the robot or not
  ip: 169.254.140.85 ## The IP address of the robot
  port: 9559 ## The port of the robot
  voice:
    0:
      name: "Pepper"
      description: "Pepper's own robot voice."

# 1. GENERAL
general:
  main_prompt_path: 'dependencies/text/prompt.txt' ## main prompt path
  robotic_voice: False ## robotic voice interference
  object_detection: False ## To use object detection
  camera_device_index: 0 ## camera device index for object detection

# 2. Google Cloud Speech API
google_cloud_speech: ## The Google Cloud Speech API key

# 3. OpenAI GPT model information
openai_gpt:
  model: "gpt-4-turbo" ## Model to use
  enable_vision: False ## Whether to enable vision API
  vision_frequency: 5 ## Time in seconds between each vision API call
  temperature: 0.7 ## Temperature for the GPT model, float between 0 and 2
  max_tokens: 300 ## Maximum number of tokens to generate.
  top_p: 1.0 ## Number of completions to generate for each prompt.

# 4. Elevenlabs API information
elevenlabs:
  use_elevenlabs: True ## Whether to use the Eleven (OVERWRITES EVERYTHING ELSE)
  init_language: 'da-DK' ## language for the model to use at the start
  multi_lingual: True ## Whether to use multi-lingual model, i.e. switch languages during conversation
  english_only_model_id: 'eleven_flash_v2' ## Model ID for the English only model
  multi_lingual_model_id: 'eleven_multilingual_v2' ## Model ID for the multi-lingual model
  init_voice: 1 ## Initial voice to use, 0 is Pepper's own voice
  enable_voice_change: True ## Whether to enable voice change
  voices: # NOTE if description is left empty, it will use the default description from the elevenlabs API
    1: 
      id: "dD4UVmm5aRLH7OY6HGtp"
      name: "Bria - Young and Soft"
      description: 
    2:
      id: "rU18Fk3uSDhmg5Xh41o4"
      name: "Ryan Kurk"
      description: "Male, bright, young, expressive narrative voice. It could soothe, excite, inform, and entertain, all at the same time."
    3:
      id: "TWGIYqyf4ytM4ctpb0S1"
      name: "Phoebe"
      description: "Female, young, playful and energetic voice, with a hint of assertiveness."
    4:
      id: "nIBoiUir3RAsl7ppOJeu"
      name: "Dave - deep and gruff"
      description: "Male, middle-aged, deep and gruff voice, raw and intimidating. "
    5:
      id: "XBIkBVE81YF3J3QG8L96"
      name: "Maya"
      description: 
    6:
      id: "gGLuLNsf9oA3WitvXpXc"
      name: "Thomas"
      description: 
